@startuml
top to bottom direction

skinparam packageStyle rectangle
skinparam actorStyle awesome

skinparam rectangle {
  borderColor black
}

rectangle {
  rectangle FAP as main #E1E1E1
  rectangle ModuleList #ADC2A9
  rectangle UI #B4A7D6
  rectangle Parser #FFD966
  rectangle Command #A2C4C9
  rectangle JsonManager #D5A6BD
  rectangle Storage #8E7CC3
  rectangle User #F9E79F
}

file DataFile #LightGrey

actor "CEG Student"

"CEG Student" --> main
main --> User
main --> ModuleList
main --> UI
main --> Parser
main --> Storage
main --> JsonManager

JsonManager --> Command
JsonManager --> Storage

Parser --> Command
Command --> UI
Command --> Storage
Storage <--.> User
Storage <.--> DataFile
Storage <--.> ModuleList

@enduml