@startuml

actor Student as "CEG Student"

participant Storage as Storage <<class>>
participant Ui as ":Ui"
participant FAP as FAP <<class>>
participant Parser as Parser <<class>>
participant Command as ":Command"
participant User as ":User"
participant ModuleList as ":ModuleList"

activate FAP
note over FAP: runApplication() infinite loop

Student -> Ui: userInput
activate Ui
Ui --> FAP: return valid userInput
deactivate Ui

FAP -> Parser: getCommand(userInput)
activate Parser
Parser --> FAP: return command instance
deactivate Parser

FAP -> Command: execute(userInput)
activate Command
Command -> Command: do stuff
Command --> FAP
deactivate Command

FAP -> User: resetModuleStatus()
activate User
User -> ModuleList: updateModuleStatus()
activate ModuleList
ModuleList --> User
deactivate ModuleList
User --> FAP
deactivate User

FAP -> Storage: saveModulesToFile(filePath)

note over FAP: until "Bye" command is sent

@enduml