@startuml

actor Student as "CEG Student"

participant FAP as FAP <<class>>
participant Storage as Storage <<class>>
participant Ui as ":Ui"
participant Parser as Parser <<class>>

activate FAP
loop until "Bye" Command

FAP -> Ui: get user input
activate Ui

Ui -> Student: scanner
Student --> Ui: userInput
Ui --> FAP: valid userInput

deactivate Ui

FAP -> Parser: getCommand(userInput)
activate Parser
Parser -> ":Command"**: new
activate ":Command"
":Command" --> Parser:
deactivate ":Command"
Parser --> FAP: return command instance
deactivate Parser

FAP -> ":Command": execute(userInput)
activate ":Command"
":Command" -> ":Command": do stuff
":Command" --> FAP
deactivate ":Command"

participant User as ":User"
participant ModuleList as ":ModuleList"

FAP -> User: resetModuleStatus()
activate User
User -> ModuleList: updateModuleStatus()
activate ModuleList
ModuleList --> User
deactivate ModuleList
User --> FAP
deactivate User

FAP -> Storage: saveModulesToFile(filePath)
":Command" -> ":Command"
destroy ":Command"
end loop
deactivate FAP

@enduml