@startuml

participant FAP
participant DesiredGpaCommand
participant GradeCommandMetadata
participant moduleList
participant InvalidGpaException
participant Ui

FAP -> DesiredGpaCommand: execute(userInput)
activate DesiredGpaCommand
DesiredGpaCommand -> GradeCommandMetadata: validateGPA(desiredGPA)
activate GradeCommandMetadata
GradeCommandMetadata --> DesiredGpaCommand
deactivate GradeCommandMetadata


DesiredGpaCommand -> moduleList: calcGradesExpectations(desiredGPA)
activate moduleList
moduleList -> moduleList: tallyGPAForCalcGradesExpectations()
moduleList -> moduleList: getValidCreditsTaken()
moduleList -> moduleList: calculate future average grade
moduleList -> moduleList: validateFutureAverageGrade()
alt
moduleList -> moduleList: calculateMockGPA()
moduleList -> Ui: printGradeExpectations()
Ui --> moduleList
moduleList --> DesiredGpaCommand
deactivate moduleList
DesiredGpaCommand --> FAP

deactivate DesiredGpaCommand

@enduml
