@startuml
skinparam participantPadding 20

participant FAP as User <<Class>>
participant ViewGpaCommand as ":ViewGpaCommand"
participant ModuleList as ":ModuleList"
participant Module as ":Module"
participant GpaNullException as ":GpaNullException"

User -> ViewGpaCommand: execute(userInput)
activate ViewGpaCommand

ViewGpaCommand -> ModuleList: tallyGPA()
activate ModuleList

Loop For each Module
    ModuleList -> Module: getModuleGrade()
    activate Module
    Module --> ModuleList: Module Grade
    alt Countable grade
        ModuleList -> Module: getModuleMC()
        Module --> ModuleList: Module credits
        ModuleList -> Module: getModuleGradeNumber()
        Module --> ModuleList: Grade number
    else Non-countable grade
        Module --> ModuleList
    end
end
    deactivate Module
    alt Total MC is zero
        ModuleList -> GpaNullException: Throw GpaNullException
        activate GpaNullException
        GpaNullException --> ModuleList: GpaNullException
        deactivate GpaNullException
        ModuleList --> ViewGpaCommand: GpaNullException
    else Calculate GPA
        ModuleList --> ViewGpaCommand: GPA
    end

ViewGpaCommand --> User

deactivate ViewGpaCommand
deactivate ModuleList
@enduml
